(async function() {
    const { GoogleSpreadsheet } = require('google-spreadsheet');

// Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('https://docs.google.com/spreadsheets/d/1-RK2h1XiSebikI5FFCO_z3BHDd8NeKrLmoTpRqXtCVg/edit#gid=48092843');

// Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
await doc.useServiceAccountAuth({
  // env var values are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  client_email: 'id-carl-google-sheets@airy-media-320501.iam.gserviceaccount.com',
  private_key: '111090094270301390986',
});


await doc.loadInfo(); // loads document properties and worksheets


const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
let data = sheet.getRows()
console.log(data);

// // adding / removing sheets
// const newSheet = await doc.addSheet({ title: 'hot new sheet!' });
// await newSheet.delete();
  }());
